### ISSUE TITLE
Offline version, how to?

### ISSUE THREAD

**Issue by linonetwo** [fboerncke/bloom-ai-simple-starter-nodejs#1]
Hi, do you know any solution that can run language model on nodejs without internet access?

I'm writing a electronjs based tiddlywiki app https://github.com/tiddly-gittly/TidGi-Desktop that is offline-first, and I want to make it possible to run a large language model (around 1GB is ok I think?).

**Comment by fboerncke** [comment]
That would be interesting indeed.

Unfortunately I never tried to get something like this up and running so I cannot help you here.

There are offline versions for stable diffusion (I am running this myself) available on GitHub, but those use pre trained models.

**Comment by linonetwo** [comment]
I just want to use pre trained language model, and fine turn locally, because I don't know much about machine learning frameworks. Maybe I can find some GPT based things... Thanks anyway.
